In [1]:
import numpy as np
import pandas as pd 
import seaborn as sns 

In [2]:
il = 2
hl = 3
op_neu = 1 

In [3]:
print(il)
print(hl)
print(op_neu)

2
3
1


In [4]:
wh = np.random.uniform(size = (il, hl))
bh = np.random.uniform(size = ( 1, hl))
wout = np.random.uniform(size = (hl, op_neu))
bout = np.random.uniform(size = (1, op_neu))

In [5]:
print(wh)
print(bh)
print(wout)
print(bout)

[[0.95598118 0.12713068 0.56151875]
 [0.07550474 0.29466613 0.77971902]]
[[0.1694906  0.73085436 0.20553579]]
[[0.00585332]
 [0.16404339]
 [0.68067587]]
[[0.8639745]]


In [6]:
epoch = 7000
lr = 0.1

def sigmond(x):
    return 1/(1+ np.exp(-x))

def derivative_sigmond(x):
    return x*(1-x)

X = np.array(([2,9],[1,5],[3,6]), dtype = float)
y = np.array(([92], [86], [89]), dtype = float)
X = X/np.amax(X, axis=0)
y = y/100

In [7]:
for i in range(epoch):
    hinp1 = np.dot(X, wh)
    hinp = hinp1 + bh
    hlayer_act = sigmond(hinp)
    
    outinp1 = np.dot(hlayer_act, wout)
    outinp = outinp1 + bout
    output = sigmond(outinp)
    
    EO = y-output
    outgrad = derivative_sigmond(output)
    d_output = EO * outgrad
    EH = d_output.dot(wout.T)
    
    hiddengrad = derivative_sigmond(hlayer_act)
    d_hiddenlayer = EH*hiddengrad
    wout += hlayer_act.T.dot(d_output)*lr
    wh += X.T.dot(d_hiddenlayer)*lr

In [8]:
print(str(X))
print(str(y))
print(output)

[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
[[0.92]
 [0.86]
 [0.89]]
[[0.89473284]
 [0.88078613]
 [0.8944181 ]]
