In [9]:
import numpy as np
import pandas as pd 
import seaborn as sns

from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

from sklearn.neighbors import KNeighborsClassifier

In [3]:
data = sns.load_dataset('iris')
x = data.iloc[: , :-1]
y = data.iloc[:, -1]

In [7]:
le = LabelEncoder()
y = le.fit_transform(y)

In [8]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [11]:
nn = KNeighborsClassifier(n_neighbors=3)
nn.fit(x_train, y_train)
y_prednn = nn.predict(x_test)

In [12]:
print(accuracy_score(y_test, y_prednn))

0.9666666666666667


In [13]:
print(confusion_matrix(y_test, y_prednn))

[[ 8  0  0]
 [ 0 10  0]
 [ 0  1 11]]
