In [1]:
import pandas as pd 
import numpy as np 

In [2]:
ip = 2
hl = 3 
op_neu = 1 


In [3]:
wh = np.random.uniform(size = (ip, hl))
bh = np.random.uniform(size = (1, hl))
wout = np.random.uniform(size = (hl, op_neu))
bout = np.random.uniform(size = (1, op_neu))

In [4]:
print(wh)
print(bh)
print(wout)
print(bout)

[[0.22397372 0.7129692  0.41215411]
 [0.0892056  0.0469989  0.2840118 ]]
[[0.85951133 0.76491659 0.2464307 ]]
[[0.42504777]
 [0.32817306]
 [0.49731879]]
[[0.54441376]]


In [5]:
epoch = 7000
lr = 0.1

def sigmond(x):
    return 1/(1+np.exp(-x))
def derivative_sigmond(x):
    return x*(1-x)

x = np.array(([2,9], [1,5], [3,6]), dtype= float)
y = np.array(([92], [86], [89]), dtype = float)
x = x/np.amax(x, axis = 0)
y = y/100

In [6]:
for i in range(epoch):
    hinp1 = np.dot(x, wh)
    hinp = hinp1 + bh
    hlayer_act = sigmond(hinp)
    
    outinp1 = np.dot(hlayer_act, wout)
    outinp = outinp1 + bout
    output = sigmond(outinp)
    
    EO = y - output
    outgrad = derivative_sigmond(output)
    d_output = EO * outgrad
    
    EH = d_output.dot(wout.T)
    hiddengrad = derivative_sigmond(hlayer_act)
    d_hidden = EH * hiddengrad
    
    wout += hlayer_act.T.dot(d_output)
    wh += x.T.dot(d_hidden)*lr

In [7]:
print("Normalized input: \n"+str(x))
print("Actual output: \n"+str(y))
print("Output: \n"+str(output))

Normalized input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual output: 
[[0.92]
 [0.86]
 [0.89]]
Output: 
[[0.89314655]
 [0.88081003]
 [0.89552598]]
