In [1]:
import pandas as pd 
import numpy as np
import seaborn as sns

from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

from sklearn.neighbors import KNeighborsClassifier



In [2]:
data = pd.read_csv("Iris.csv")

In [3]:
x = data.iloc[:, : -1]
y = data.iloc[:, -1]

In [4]:
le = LabelEncoder()
y = le.fit_transform(y)

In [5]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
x_test, x_train, y_test, y_train = train_test_split(x, y, test_size=0.2)

In [7]:
nn = KNeighborsClassifier(n_neighbors=3)
nn.fit(x_train, y_train)
y_pred = nn.predict(x_test)

In [12]:
print("Accuracy Score: \n" , accuracy_score(y_test, y_pred))

Accuracy Score: 
 0.925


In [11]:
print("Confusion Matrix:\n" , confusion_matrix(y_test, y_pred))

Confusion Matrix:
 [[40  0  0]
 [ 3 36  0]
 [ 0  6 35]]
