In [1]:
import numpy as np
import pandas as pd 
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB


import seaborn as sns 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder



In [2]:
data = sns.load_dataset('iris')


In [3]:
data

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [4]:
x = data.iloc[:, :-1].values

In [5]:
y = data.iloc[:, -1].values

In [6]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [7]:
y

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolo

In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [9]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2)

In [10]:
dt = DecisionTreeClassifier(criterion='entropy')
dt.fit(x_train, y_train)
y_pred = dt.predict(x_test)

In [11]:
gb = GaussianNB()
gb.fit(x_train, y_train)
y_predgb = gb.predict(x_test)

In [12]:
nn = KNeighborsClassifier(n_neighbors=3)
nn.fit(x_train, y_train)
y_prednn = nn.predict(x_test)

In [13]:
from sklearn.metrics import accuracy_score, confusion_matrix
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

1.0
[[10  0  0]
 [ 0 10  0]
 [ 0  0 10]]


In [14]:
print(accuracy_score(y_test, y_prednn))
print(confusion_matrix(y_test, y_prednn))

1.0
[[10  0  0]
 [ 0 10  0]
 [ 0  0 10]]


In [15]:
print(accuracy_score(y_test, y_predgb))
print(confusion_matrix(y_test, y_predgb))

1.0
[[10  0  0]
 [ 0 10  0]
 [ 0  0 10]]


In [16]:
def n(a):
    if a == 0:
        return "setosa"
    elif a == 1 :
        return "bcub"
    else :
        return "ccccc"

In [17]:
for i in range(len(x_test)):
    print(f"Actual : {x_test[i]}, Class Label {n(y_test[i])}, predicted {n(y_pred[i])}")

Actual : [6.3 2.3 4.4 1.3], Class Label bcub, predicted bcub
Actual : [7.2 3.2 6.  1.8], Class Label ccccc, predicted ccccc
Actual : [5.5 3.5 1.3 0.2], Class Label setosa, predicted setosa
Actual : [6.4 3.2 4.5 1.5], Class Label bcub, predicted bcub
Actual : [5.  3.  1.6 0.2], Class Label setosa, predicted setosa
Actual : [6.7 3.3 5.7 2.5], Class Label ccccc, predicted ccccc
Actual : [5.1 3.8 1.9 0.4], Class Label setosa, predicted setosa
Actual : [5.7 2.6 3.5 1. ], Class Label bcub, predicted bcub
Actual : [6.7 3.1 5.6 2.4], Class Label ccccc, predicted ccccc
Actual : [4.9 3.  1.4 0.2], Class Label setosa, predicted setosa
Actual : [7.  3.2 4.7 1.4], Class Label bcub, predicted bcub
Actual : [6.9 3.1 5.1 2.3], Class Label ccccc, predicted ccccc
Actual : [5.5 2.6 4.4 1.2], Class Label bcub, predicted bcub
Actual : [5.1 3.4 1.5 0.2], Class Label setosa, predicted setosa
Actual : [6.5 3.2 5.1 2. ], Class Label ccccc, predicted ccccc
Actual : [6.2 2.2 4.5 1.5], Class Label bcub, predicted

In [21]:
for i in range(len(x_test)):    
    print(f"Actual : {x_test[i]}, Class Label:{(y_test[i])}, predicted: {y_pred[i]}")

Actual : [6.3 2.3 4.4 1.3], Class Label:1, predicted: 1
Actual : [7.2 3.2 6.  1.8], Class Label:2, predicted: 2
Actual : [5.5 3.5 1.3 0.2], Class Label:0, predicted: 0
Actual : [6.4 3.2 4.5 1.5], Class Label:1, predicted: 1
Actual : [5.  3.  1.6 0.2], Class Label:0, predicted: 0
Actual : [6.7 3.3 5.7 2.5], Class Label:2, predicted: 2
Actual : [5.1 3.8 1.9 0.4], Class Label:0, predicted: 0
Actual : [5.7 2.6 3.5 1. ], Class Label:1, predicted: 1
Actual : [6.7 3.1 5.6 2.4], Class Label:2, predicted: 2
Actual : [4.9 3.  1.4 0.2], Class Label:0, predicted: 0
Actual : [7.  3.2 4.7 1.4], Class Label:1, predicted: 1
Actual : [6.9 3.1 5.1 2.3], Class Label:2, predicted: 2
Actual : [5.5 2.6 4.4 1.2], Class Label:1, predicted: 1
Actual : [5.1 3.4 1.5 0.2], Class Label:0, predicted: 0
Actual : [6.5 3.2 5.1 2. ], Class Label:2, predicted: 2
Actual : [6.2 2.2 4.5 1.5], Class Label:1, predicted: 1
Actual : [5.2 2.7 3.9 1.4], Class Label:1, predicted: 1
Actual : [6.5 3.  5.8 2.2], Class Label:2, predi