In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
il = 2
hl = 3
op_neu = 1

In [3]:
print(f'Number of neurons in input layer : {il}')
print(f'Number of neurons in hidden layer   : {hl}')
print(f'Number of neurons in output layer   : {op_neu}')

Number of neurons in input layer : 2
Number of neurons in hidden layer   : 3
Number of neurons in output layer   : 1


In [4]:
wh=np.random.uniform(size=(il,hl))
bh=np.random.uniform(size=(1,hl))
wout=np.random.uniform(size=(hl,op_neu))
bout=np.random.uniform(size=(1,op_neu))

In [5]:
print(f'Weights from input layer to hidden layer :\n {wh}')
print(f'Bias in input layer to hidden layer :\n {bh}')
print(f'Weights from hidden layer to output layer:\n {wout}')
print(f'Bias in hidden layer to output layer:\n {bout}')

Weights from input layer to hidden layer :
 [[0.68564063 0.01642175 0.73459746]
 [0.07984453 0.99846607 0.13400184]]
Bias in input layer to hidden layer :
 [[0.28194127 0.40758587 0.55417383]]
Weights from hidden layer to output layer:
 [[0.74938861]
 [0.40159321]
 [0.36378862]]
Bias in hidden layer to output layer:
 [[0.83788546]]


In [6]:
epoch=7000              
lr=0.1 

def sigmoid (x):
    return 1/(1 + np.exp(-x))

def derivatives_sigmoid(x):
    return x * (1 - x)

In [7]:
X = np.array(([2, 9], [1, 5], [3, 6]), dtype=float)
y = np.array(([92], [86], [89]), dtype=float)
X = X/np.amax(X,axis=0) 
y = y/100

In [12]:
for i in range(epoch):

    hinp1=np.dot(X,wh)
    hinp=hinp1 + bh
    hlayer_act = sigmoid(hinp)
    outinp1=np.dot(hlayer_act,wout)
    outinp= outinp1+ bout
    output = sigmoid(outinp)

    EO = y-output
    outgrad = derivatives_sigmoid(output)
    d_output = EO* outgrad
    EH = d_output.dot(wout.T)

    hiddengrad = derivatives_sigmoid(hlayer_act)
    d_hiddenlayer = EH * hiddengrad
    
    wout += hlayer_act.T.dot(d_output) *lr
    wh += X.T.dot(d_hiddenlayer) *lr

In [9]:
print("Input: \n" + str(X))
print("Actual Output: \n" + str(y))
print("Predicted Output: \n" ,output)

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
 [[0.89375177]
 [0.88154704]
 [0.894972  ]]
